### ISSUE TITLE
Installation impossible avec autoupdate (up)

### ISSUE THREAD

**Issue by Cluster45** [OGSteam/mod-emspyre#4]
Le fichier fichier version.txt semble incorrect

![image](https://user-images.githubusercontent.com/54951699/64363596-5e805180-d011-11e9-9c65-1c5afbf8789d.png)

![image](https://user-images.githubusercontent.com/54951699/64363645-735ce500-d011-11e9-9eb0-f3b24668bf11.png)

**Comment by machine62** [comment]
il semble que le correctif n'avait jamais ete mis en release

**Comment by Cluster45** [comment]
Toujours le problème sur le serveur de Darknoon.
